version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - mongodb
      - redis
      - minio
    env_file: 
      - .env
    ports:
      - "3000:3000"
    networks:
      - app_network

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  ### Redis ###
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  ### MinIO (локальный S3) ###
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # API для загрузки файлов
      - "9001:9001"  # Веб-интерфейс
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app_network

  ### MinIO Client (для создания бакета) ###
  minio_setup:
    image: minio/mc
    container_name: minio_mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb local/my-bucket;
      mc policy set public local/my-bucket;
      exit 0;
      "
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
  minio_data:
